/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `scorekinole-${version}`;

// Assets generated by the build process (JS, CSS chunks with hashed filenames)
const BUILD_ASSETS = build;

// Static files in /static (exclude large files)
const STATIC_ASSETS = files.filter(
	(f) => !f.endsWith('.png') || f.includes('icon-')
);

const ALL_ASSETS = [...BUILD_ASSETS, ...STATIC_ASSETS];
const ASSET_SET = new Set(ALL_ASSETS);

// Install: cache all build + essential static assets + SPA shell
sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then(async (cache) => {
				await cache.addAll(ALL_ASSETS);
				await cache.add('/'); // SPA shell for offline navigation fallback
			})
			.then(() => sw.skipWaiting())
	);
});

// Activate: clean up old caches
sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches
			.keys()
			.then((keys) =>
				Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
			)
			.then(() => sw.clients.claim())
	);
});

// Fetch: network-first for navigation, cache-first for assets
sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Skip non-HTTP(S) requests
	if (!url.protocol.startsWith('http')) return;

	// Skip Firebase/external API calls - always go to network
	if (url.hostname !== sw.location.hostname) return;

	// For app assets: cache-first with write-back on cache miss
	if (ASSET_SET.has(url.pathname)) {
		event.respondWith(
			caches.match(event.request).then((cached) => {
				if (cached) return cached;
				return fetch(event.request).then((response) => {
					const clone = response.clone();
					caches.open(CACHE_NAME).then((c) => c.put(event.request, clone));
					return response;
				});
			})
		);
		return;
	}

	// For HTML navigation: network-first with offline fallback to cached SPA shell
	if (event.request.mode === 'navigate') {
		event.respondWith(
			fetch(event.request).catch(() => caches.match('/') as Promise<Response>)
		);
		return;
	}
});

// Push notification handler
sw.addEventListener('push', (event) => {
	let title = 'Scorekinole';
	let body = '';
	let icon = '/icon-192.png';
	let url = '/';
	let tag = '';

	try {
		const raw = event.data?.json() ?? {};
		// FCM data-only messages may arrive flat or nested under "data"
		const payload = raw.data && typeof raw.data === 'object' && raw.data.title
			? raw.data
			: raw;
		title = payload.title || 'Scorekinole';
		body = payload.body || '';
		icon = payload.icon || '/icon-192.png';
		url = payload.url || '/';
		tag = payload.tag || '';
	} catch {
		// JSON parse failed — show generic notification
	}

	event.waitUntil(
		sw.registration.showNotification(title, {
			body,
			icon,
			badge: '/icon-192.png',
			data: { url },
			tag: tag || undefined,
			...( tag ? { renotify: true } : {} )
		} as NotificationOptions)
	);
});

// Click on notification → navigate existing app window or open new one
sw.addEventListener('notificationclick', (event) => {
	event.notification.close();
	const targetUrl = event.notification.data?.url || '/';
	const absoluteUrl = new URL(targetUrl, sw.location.origin).href;

	event.waitUntil(
		sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(async (clients) => {
			// Prefer a client already on the exact target URL — focus and notify it
			for (const client of clients) {
				if (new URL(client.url).href === absoluteUrl && 'focus' in client) {
					// Still send postMessage so the app can re-process the deep-link
					// (e.g., two notifications for same tournament, or URL cleanup hasn't run yet)
					(client as WindowClient).postMessage({ type: 'PUSH_NAVIGATE', url: targetUrl });
					return client.focus();
				}
			}
			// Try to navigate an existing app window to the target URL
			for (const client of clients) {
				if ('navigate' in client && 'focus' in client) {
					try {
						const navigated = await (client as WindowClient).navigate(absoluteUrl);
						if (navigated) {
							// Also postMessage as fallback — navigate() may not work reliably
							// on Android PWAs when the app is in background
							navigated.postMessage({ type: 'PUSH_NAVIGATE', url: targetUrl });
							return navigated.focus();
						}
					} catch {
						// navigate() failed on this client — try postMessage + focus instead
						try {
							(client as WindowClient).postMessage({ type: 'PUSH_NAVIGATE', url: targetUrl });
							return (client as WindowClient).focus();
						} catch {
							// this client is unusable — try next one
						}
					}
				}
			}
			// No existing windows or all navigate attempts failed — open new window
			return sw.clients.openWindow(absoluteUrl);
		})
	);
});
