/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `scorekinole-${version}`;

// Assets generated by the build process (JS, CSS chunks with hashed filenames)
const BUILD_ASSETS = build;

// Static files in /static (exclude large files)
const STATIC_ASSETS = files.filter(
	(f) => !f.endsWith('.png') || f.includes('icon-')
);

const ALL_ASSETS = [...BUILD_ASSETS, ...STATIC_ASSETS];

// Install: cache all build + essential static assets
sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ALL_ASSETS))
			.then(() => sw.skipWaiting())
	);
});

// Activate: clean up old caches
sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches
			.keys()
			.then((keys) =>
				Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
			)
			.then(() => sw.clients.claim())
	);
});

// Fetch: network-first for navigation, cache-first for assets
sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Skip non-HTTP(S) requests
	if (!url.protocol.startsWith('http')) return;

	// Skip Firebase/external API calls - always go to network
	if (url.hostname !== sw.location.hostname) return;

	// For app assets: cache-first (they have hashed filenames, safe to cache)
	if (ALL_ASSETS.includes(url.pathname)) {
		event.respondWith(
			caches.match(event.request).then((cached) => cached || fetch(event.request))
		);
		return;
	}

	// For HTML navigation: network-first with offline fallback
	if (event.request.mode === 'navigate') {
		event.respondWith(
			fetch(event.request).catch(() => caches.match('/index.html') as Promise<Response>)
		);
		return;
	}
});

// Push notification handler
sw.addEventListener('push', (event) => {
	const data = event.data?.json() ?? {};
	const { title, body, icon, url, tag } = data;

	event.waitUntil(
		sw.registration.showNotification(title || 'Scorekinole', {
			body: body || '',
			icon: icon || '/icon-192.png',
			badge: '/icon-192.png',
			data: { url: url || '/' },
			tag: tag,
			renotify: !!tag
		})
	);
});

// Click on notification → open/focus the app at the correct URL
sw.addEventListener('notificationclick', (event) => {
	event.notification.close();
	const url = event.notification.data?.url || '/';

	event.waitUntil(
		sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
			for (const client of clients) {
				if (new URL(client.url).pathname === url && 'focus' in client) {
					return client.focus();
				}
			}
			return sw.clients.openWindow(url);
		})
	);
});
